site_name: 小C




nav:
    - Usage: index.md
    - Customization: about.md
    - Samples:
        - Sample Page A: stock/index.md
        - Sample Subfolder:
            - Sample Subpage A1: sample-a1.md
            - Sample Subpage A2: sample-a2.md
        - Sample Page B: sample-b.md


# 安装 mkdocs
# pip install mkdocs mkdocs-material
# pip install mkdocs-windmill-dark
# theme:
  # name: material


theme: mkdocs
  # name: nil
  # # custom_dir: mkdocs_windmill_dark
  # static_templates:
  #     - 404.html
  # include_search_page: true
  # search_index_only: true
  # history_buttons: true
  # article_nav_top: true
  # article_nav_bottom: true
